---
- name: Install Prometheus
  hosts: vm
  become: true
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Download Grafana key
      get_url:
        url: https://packages.grafana.com/gpg.key
        dest: ./grafana-gpg.key  # Corrected version number

    - name: Add Grafana GPG Key
      become: yes
      command: sudo apt-key add ./grafana-gpg.key

    - name: Add the Grafana repository to APT sources
      become: yes
      command: sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
    - name: Update APT cache
      apt:
       update_cache: yes
    - name: Install Grafana
      become: yes
      apt:
        name: grafana
        state: present
        update_cache: yes
    - name: Start Grafana Server
      systemd:
        name: grafana-server
        state: started
        enabled: yes