---
- name: Update hosts
  hosts: localhost
 # become: true
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    resource_group_name: pfa
    vm_name: "VirtualMachine"
    ansible_user: "louaykharouf"
    ansible_ssh_pass: "PassStudent123"
  tasks: 
  - name: trigger the API
    shell: az vm show -d -g VirtualMachine1 -n {{ vm_name }} --query publicIps -o tsv
    register: publicIP
  - name: update the host file
    lineinfile: 
     dest: ./hosts
     line: "{{ publicIP.stdout }} ansible_user={{ ansible_user }} ansible_ssh_pass={{ ansible_ssh_pass }}"
     insertafter: EOF
